services:
  cloudgamecatalog.api:
    image: ${DOCKER_REGISTRY-}cloudgamecatalogapi
    build:
      context: .
      dockerfile: ./src/CloudGameCatalog.Api/Dockerfile
    user: "root"
    ports:
      - '57398:8080'
      - '57399:8081'
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false      
      - ASPNETCORE_ENVIRONMENT=Docker
      - DOTNET_ENVIRONMENT=Docker      
    volumes:
    - ./src/CloudGameCatalog.Api/Logs:/app/Logs
    restart: unless-stopped    
    networks:
      - cloudgame-network

  cloudgamecatalog.consumer:
    image: ${DOCKER_REGISTRY-}cloudgamecatalogconsumer
    build:
      context: .
      dockerfile: ./src/CloudGameCatalog.Consumer/Dockerfile
    user: "root"
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - ASPNETCORE_ENVIRONMENT=Docker
      - DOTNET_ENVIRONMENT=Docker      
    volumes:
    - ./src/CloudGameCatalog.Consumer/Logs:/app/Logs
    restart: unless-stopped        
    networks:
      - cloudgame-network  

networks:
  cloudgame-network:
    external: true
    name: cloudgame-network